version: '3.3'

services:
  iopac:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
    - ./config.yaml:/app/config.yaml
    restart: always
    ports:
    - 8080:8080
    environment:
    - SLEEP_TIME=600
