services:
  iopac:
    build:
      context: .
      dockerfile: Dockerfile.rs
    volumes:
    - ./config.yaml:/app/config.yaml
    restart: always
    ports:
    - 8080:8080
    environment:
      TZ: Europe/Berlin
      SLEEP_TIME: 600
      PORT: 8080
      CONFIG_FILE: config.yaml
      ICS_FILE: iopac.ics
      ICS_PATH: /iopac.ics
      EVENT_NAME: Bücherei Rückgabe
